# Generated by Django 5.2.9 on 2026-01-03 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(help_text='Cloudflare API token with DNS edit permission', max_length=255)),
                ('default_zone_id', models.CharField(blank=True, help_text='Default Zone ID for domains', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloudflare Settings',
                'verbose_name_plural': 'Cloudflare Settings',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain name (e.g., example.com)', max_length=255, unique=True)),
                ('wp_username', models.CharField(blank=True, max_length=150)),
                ('wp_password', models.CharField(blank=True, help_text='Encrypted password', max_length=255)),
                ('wp_admin_email', models.EmailField(blank=True, max_length=254)),
                ('is_fresh_installation', models.BooleanField(default=False, help_text='True if credentials were auto-generated')),
                ('is_verified', models.BooleanField(default=False, help_text='True if credentials have been verified')),
                ('cloudflare_zone_id', models.CharField(blank=True, help_text='Override zone ID for this domain', max_length=64)),
                ('server_ip', models.GenericIPAddressField(blank=True, help_text='Server IP for DNS A record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, help_text='Encrypted password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Proxy Settings',
                'verbose_name_plural': 'Proxy Settings',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('cerebras', 'Cerebras'), ('flux', 'Flux'), ('nanobanana', 'Nanobanana')], max_length=50)),
                ('api_key', models.CharField(help_text='API key (encrypted)', max_length=255)),
                ('model_name', models.CharField(blank=True, help_text='e.g., llama-3.3-70b-versatile', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'unique_together': {('site', 'provider')},
            },
        ),
    ]
