# Generated by Django 5.2.9 on 2026-01-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the keyword list (from filename)', max_length=255)),
                ('keywords_json', models.JSONField(help_text='JSON array of H2 heading sets')),
                ('item_count', models.IntegerField(default=0, help_text='Number of H2 sets in the list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword List',
                'verbose_name_plural': 'Keyword Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_index', models.IntegerField(default=0, help_text='Index of H2 set in keyword list')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('introduction', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('faq_json', models.JSONField(blank=True, default=dict, help_text='H2 -> Answer pairs')),
                ('content_html', models.TextField(blank=True, help_text='Full rendered HTML')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('wp_post_id', models.IntegerField(blank=True, help_text='WordPress post ID after publishing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.site')),
                ('keyword_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='dashboard.keywordlist')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
