# Generated by Django 5.2.9 on 2026-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_keywordlist_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='wp_app_password',
            field=models.CharField(blank=True, help_text='WordPress Application Password for REST API', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='wp_password',
            field=models.CharField(blank=True, help_text='WP Admin password', max_length=255),
        ),
    ]
