# Generated by Django 5.2.9 on 2026-01-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_site_wp_app_password_alter_site_wp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wp_post_url',
            field=models.URLField(blank=True, help_text='WordPress post permalink', max_length=500),
        ),
    ]
