# Generated by Django 5.2.9 on 2026-01-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_article_wp_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('source', models.CharField(choices=[('groq', 'Groq API'), ('wordpress', 'WordPress'), ('system', 'System')], default='system', max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context (article_id, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Site Log',
                'verbose_name_plural': 'Site Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
