# Generated by Django 5.2.9 on 2026-01-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sitelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.IntegerField(help_text='Target number of articles to generate')),
                ('completed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('start_time', models.TimeField(default='05:00', help_text='Time to start generating articles (UTC)')),
                ('end_time', models.TimeField(default='01:00', help_text='Time to finish generating articles (UTC)')),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_runs', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Daily Run',
                'verbose_name_plural': 'Daily Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
