# Generated by Django 5.2.9 on 2026-01-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dailyrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrun',
            name='keyword_list',
            field=models.ForeignKey(blank=True, help_text='Keyword list to use for article generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.keywordlist'),
        ),
    ]
