# Generated by Django 5.2.10 on 2026-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dailyrun_keyword_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['provider'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='provider',
            field=models.CharField(choices=[('groq', 'Groq'), ('sambanova', 'SambaNova'), ('cerebras', 'Cerebras')], max_length=50),
        ),
    ]
