# Generated by Django 5.2.10 on 2026-01-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_apikey_options_alter_apikey_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='daily_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='dashboard.dailyrun'),
        ),
        migrations.AddField(
            model_name='article',
            name='generation_info',
            field=models.JSONField(blank=True, default=dict, help_text='Provider, model, and generation stats'),
        ),
        migrations.AddField(
            model_name='article',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for force kill', max_length=100),
        ),
    ]
