# Generated by Django 5.2.11 on 2026-02-22 00:28

from django.db import migrations, models


def populate_run_numbers(apps, schema_editor):
    DailyRun = apps.get_model('dashboard', 'DailyRun')
    # Assign sequential numbers per site
    sites = DailyRun.objects.values_list('site_id', flat=True).distinct()
    for site_id in sites:
        for i, run in enumerate(DailyRun.objects.filter(site_id=site_id).order_by('created_at'), start=1):
            run.run_number = i
            run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_article_daily_run_article_generation_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrun',
            name='run_number',
            field=models.PositiveIntegerField(default=0, help_text='Per-site run number (auto-incremented)'),
        ),
        migrations.RunPython(populate_run_numbers, migrations.RunPython.noop),
    ]
