# Generated by Django 5.2.11 on 2026-02-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dailyrun_run_number_alter_dailyrun_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrun',
            unique_together={('site', 'run_number')},
        ),
    ]
