# Generated by Django 5.2.11 on 2026-02-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_dailyrun_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Is auto-pilot turned on?')),
                ('target_count', models.IntegerField(default=10, help_text='Articles to generate per day')),
                ('start_time', models.TimeField(default='05:00', help_text='Time to start generating articles (UTC)')),
                ('end_time', models.TimeField(default='01:00', help_text='Time to finish generating articles (UTC)')),
                ('last_run_date', models.DateField(blank=True, help_text='The date of the last triggered automated run', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword_list', models.ForeignKey(blank=True, help_text='Keyword list to use for generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.keywordlist')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Site Automation',
                'verbose_name_plural': 'Site Automations',
            },
        ),
    ]
