# Generated by Django 5.2.11 on 2026-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_siteautomation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteautomation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='siteautomation',
            name='last_run_date',
        ),
        migrations.RemoveField(
            model_name='siteautomation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='siteautomation',
            name='target_count',
        ),
        migrations.AddField(
            model_name='siteautomation',
            name='next_run_time',
            field=models.DateTimeField(blank=True, help_text='The exact time when the next 24-hour cycle should fire.', null=True),
        ),
    ]
