# Generated by Django 5.2.11 on 2026-03-04 23:05
# Modified: use IF NOT EXISTS for flag_reason/is_flagged since they may already
# exist on servers that had the earlier short migration applied.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_siteautomation_end_time_and_more'),
    ]

    operations = [
        # Use RunSQL so ADD COLUMN is skipped if columns already exist (PostgreSQL 9.6+)
        migrations.RunSQL(
            sql="""
                ALTER TABLE dashboard_apikey
                    ADD COLUMN IF NOT EXISTS flag_reason VARCHAR(255) NOT NULL DEFAULT '';
                ALTER TABLE dashboard_apikey
                    ADD COLUMN IF NOT EXISTS is_flagged BOOLEAN NOT NULL DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE dashboard_apikey DROP COLUMN IF EXISTS flag_reason;
                ALTER TABLE dashboard_apikey DROP COLUMN IF EXISTS is_flagged;
            """,
            # Keep Django's state in sync even though we use raw SQL
            state_operations=[
                migrations.AddField(
                    model_name='apikey',
                    name='flag_reason',
                    field=models.CharField(blank=True, help_text='Reason the key was flagged', max_length=255),
                ),
                migrations.AddField(
                    model_name='apikey',
                    name='is_flagged',
                    field=models.BooleanField(default=False, help_text='Key permanently banned/restricted by provider'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_tag', models.CharField(help_text='Amazon affiliate tag, e.g. mysite-20', max_length=100)),
                ('insert_after_paragraph', models.PositiveIntegerField(default=1, help_text='Insert product block after this paragraph number (1 = after intro paragraph)')),
                ('max_products', models.PositiveIntegerField(default=3, help_text='Maximum number of products to show per article (1-5)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_config', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Affiliate Config',
                'verbose_name_plural': 'Affiliate Configs',
            },
        ),
        migrations.CreateModel(
            name='AffiliateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('affiliate_tag', models.CharField(blank=True, max_length=100)),
                ('insert_after_paragraph', models.PositiveIntegerField(default=1)),
                ('max_products', models.PositiveIntegerField(default=3)),
                ('total_articles', models.IntegerField(default=0, help_text='Total WP posts fetched')),
                ('processed', models.IntegerField(default=0, help_text='Articles attempted')),
                ('skipped', models.IntegerField(default=0, help_text='Already had amazon-prd block')),
                ('injected', models.IntegerField(default=0, help_text='Successfully injected')),
                ('errors', models.IntegerField(default=0, help_text='Failed articles')),
                ('log_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_jobs', to='dashboard.site')),
            ],
            options={
                'verbose_name': 'Affiliate Job',
                'verbose_name_plural': 'Affiliate Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
