# Generated by Django 5.2.11 on 2026-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_apikey_flag_reason_apikey_is_flagged_affiliateconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatejob',
            name='slugs_json',
            field=models.JSONField(blank=True, default=list, help_text='List of WP slugs to process'),
        ),
    ]
